name: bkoepke
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f5fb'
    - '#ee6758'
    - '#7facda'
    - '#231f20'
    - '#fed031'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
